### ISSUE TITLE
Multiple buttons in a page

### ISSUE THREAD

**Issue by silentkillerr** [cshold/social-sharing-buttons#5]
Hi,

How to use multiple share buttons in a single page

**Comment by cshold** [comment]
Include the `.social-sharing` div as many times as you would like. Change the `data-permalink` attribute to what link you want to share for each set of buttons.

Then you'll have to customize the JS so that each button makes a separate API request to get the number of shares. Use jQuery's `.each()` function ([here](http://api.jquery.com/each/)) to do that, and put the API calls inside that.

Word of warning, you may reach an API limit or drastically slow down your site if too many share buttons are used on a single page.
